### ISSUE TITLE
[Steam status] Steam is not running problem

### ISSUE THREAD

**Issue by Curyn** [JonasNilson/idle_master_extended#265] opened 2022-01-16 01:14 UTC
![image](https://user-images.githubusercontent.com/97814624/149643521-fa96fb4d-20da-4745-ae90-96c688d5e222.png)
steam is running but idle master doesnt recognized it, ive tried everything the guides say.
help pls

**Comment by JonasNilson** [comment] 2022-01-17 08:45
Have you tried using: `File -> Settings -> Ignore Steam client status`?
* ![image](https://user-images.githubusercontent.com/5990550/149736089-3a6f8f02-296d-468c-9043-f3f8f805d2cb.png)

This issue seem to be pretty common and is usually caused by having Steam running as Administrator:
* ![image](https://user-images.githubusercontent.com/5990550/149736765-68fe18f3-cd30-4ba0-a3fd-ffa78e4a3902.png)

**Comment by JonasNilson** [comment] 2022-03-09 16:45
https://github.com/JonasNilson/idle_master_extended/wiki/Steam-is-not-running

Closing this issue.

**Closed by JonasNilson** 2022-03-09 16:45 UTC
