### ISSUE TITLE
[BUG] Sign in button 100% FIX PT BR 

### ISSUE THREAD

**Issue by ShizouOrihasi** [JonasNilson/idle_master_extended#309] opened 2022-06-30 05:23 UTC
FIX 100% Functional     https://www.youtube.com/watch?v=Qn60ACpzDR8 

Video 2020 (2022) 100% FIX

**Comment by etson32** [comment] 2022-06-30 15:06
Obrigado muito fácil.

**Comment by FLUFIK12** [comment] 2022-06-30 19:52
doesn't work

**Comment by JonasNilson** [comment] 2022-07-03 14:02
Basically a duplicate of: https://github.com/JonasNilson/idle_master_extended/issues/310

**Closed by JonasNilson** 2022-07-03 14:02 UTC
Labels: bug
