### ISSUE TITLE
Everlasting "process"

### ISSUE THREAD

**Issue by Mogekoff** [JonasNilson/idle_master_extended#24] opened 2019-12-02 14:57 UTC
![image](https://user-images.githubusercontent.com/26386607/69969119-9bd77b00-153d-11ea-89be-b72cbdba70b9.png)

**Comment by JonasNilson** [comment] 2019-12-02 16:50
Do you have more info on what's happening?

**Comment by SkebbZ** [comment] 2019-12-21 08:24
Stopped working a while ago for me, just says "X games to idle, 0 games idling now. Currently ingame: Game Name"

Yes, it actually says Game Name.

**Comment by JonasNilson** [comment] 2019-12-23 12:26
@SkebbZ Is this still an issue?

**Comment by SkebbZ** [comment] 2019-12-23 20:57
@JonasNilson 
![Merknad 2019-12-23 215333](https://user-images.githubusercontent.com/12503022/71380260-ca8dc200-25ce-11ea-8748-8174e6e9dedb.png)

Also, I've selected English but only **parts** of the Settings (and drop down menus up top) are actually English.

Is there some file outside the main folder where settings are kept? Would like to try deleting that if that's the case.

**Comment by JonasNilson** [comment] 2019-12-24 12:23
@SkebbZ I guess you have restarted the client? I believe the selected language should fully work after a restart.

I would have to look into the language part if that's not the case (I'm not the original developer)

**Comment by SkebbZ** [comment] 2019-12-24 21:20
> 
> 
> @SkebbZ I guess you have restarted the client? I believe the selected language should fully work after a restart.
> 
> I would have to look into the language part if that's not the case (I'm not the original developer)

Yes, I've tried restarting/switching back and forth multiple times. Looks like I'm stuck with this mish mash of system language and English. Then again it's mostly an annoyance.

It still doesn't actually work though. Nothing starts idling.

**Comment by JonasNilson** [comment] 2019-12-25 17:06
@SkebbZ Sounds like an annoying bug. Have you tried running a freshly downloaded version and see if it works?

**Comment by SkebbZ** [comment] 2019-12-25 17:48
> 
> 
> @SkebbZ Sounds like an annoying bug. Have you tried running a freshly downloaded version and see if it works?

I have tried that, yes. Thats why I asked about any config files. 

I just found a couple lying around the C: drive and deleted them, that fixed the language issue. The main issue about not idling anything still remains.

**Comment by defenderix** [comment] 2019-12-28 11:32
i have this problem too .
https://steamuserimages-a.akamaihd.net/ugc/792003508800492211/18C2B6DFC1CA26413266E4D4783BAC37A237AAD6/
how can i solve it?

**Comment by JonasNilson** [comment] 2019-12-28 11:48
> i have this problem too .
> https://steamuserimages-a.akamaihd.net/ugc/792003508800492211/18C2B6DFC1CA26413266E4D4783BAC37A237AAD6/
> how can i solve it?

* I am not able to reproduce it at the moment:
![image](https://user-images.githubusercontent.com/5990550/71543131-04b0e800-2970-11ea-86ff-f7748eaf897d.png)

Can you look under: `C:\Users\<Your username>\AppData\Local\IdleMaster` and see if deleting the configuration files help?

**Comment by BloodyGoat** [comment] 2019-12-28 16:31
Ja zrobiłem wszystko co podpowiadacie dalej nic

**Comment by SkebbZ** [comment] 2019-12-29 00:09
@JonasNilson 
These are the files I mentioned earlier which solved my language issue. Sadly it still won't idle any games.

**Comment by JonasNilson** [comment] 2020-01-23 09:28
> @JonasNilson
> 
> > Can you look under: C:\Users<Your username>\AppData\Local\IdleMaster and see if deleting the configuration files help?
> 
> These are the files I mentioned earlier which solved my language issue. Sadly it still won't idle any games.

Have you managed to get past this issue?

**Comment by SkebbZ** [comment] 2020-01-23 19:36
> 
> 
> > @JonasNilson
> > > Can you look under: C:\Users\AppData\Local\IdleMaster and see if deleting the configuration files help?
> > 
> > 
> > These are the files I mentioned earlier which solved my language issue. Sadly it still won't idle any games.
> 
> Have you managed to get past this issue?

Sadly not :)

**Comment by JonasNilson** [comment] 2020-01-23 19:49
@SkebbZ 

Could you try running Idle Master through Visual Studio and see if you can get an error message?

**Comment by SkebbZ** [comment] 2020-01-24 22:49
> 
> 
> @SkebbZ
> 
> Could you try running Idle Master through Visual Studio and see if you can get an error message?

Tried it, but now I can no longer login as per issue #27 

```
  | Name | Value | Type
-- | -- | -- | --
◢ | $exception | {"System.DBNull contains no definition for OuterHtml"} | Microsoft.CSharp.RuntimeBinder.RuntimeBinderException
```

Triggers when I hit login

**Comment by JonasNilson** [comment] 2020-01-25 20:18
> > @SkebbZ
> > Could you try running Idle Master through Visual Studio and see if you can get an error message?
> 
> Tried it, but now I can no longer login as per issue #27
> 
> ```
>   | Name | Value | Type
> -- | -- | -- | --
> ◢ | $exception | {"System.DBNull contains no definition for OuterHtml"} | Microsoft.CSharp.RuntimeBinder.RuntimeBinderException
> ```
> 
> Triggers when I hit login

I was not able to reproduce this issue.

Can you try using the newest release: https://github.com/JonasNilson/idle_master_extended/releases/tag/v1.4 to see if you can get past the login step?

**Comment by SkebbZ** [comment] 2020-01-26 14:22
> 
> 
> > > @SkebbZ
> > > Could you try running Idle Master through Visual Studio and see if you can get an error message?
> > 
> > 
> > Tried it, but now I can no longer login as per issue #27
> > ```
> >   | Name | Value | Type
> > -- | -- | -- | --
> > ◢ | $exception | {"System.DBNull contains no definition for OuterHtml"} | Microsoft.CSharp.RuntimeBinder.RuntimeBinderException
> > ```
> > 
> > 
> > Triggers when I hit login
> 
> I was not able to reproduce this issue.
> 
> Can you try using the newest release: https://github.com/JonasNilson/idle_master_extended/releases/tag/v1.4 to see if you can get past the login step?

Tried the new release. Hit sign in, login window popped up and closed. Nothing happened.
Hit sign in again. Login window popped up again, redirected to my steam profile and closed.
Now everything seems to work :)
Games are idling again as well.

**Comment by JonasNilson** [comment] 2020-01-26 19:00
@SkebbZ

Thanks for the feedback. I will check out the issue of the login window closing too soon.

**Comment by JonasNilson** [comment] 2020-02-02 16:36
> > > > @SkebbZ
> > > > Could you try running Idle Master through Visual Studio and see if you can get an error message?
> > > 
> > > 
> > > Tried it, but now I can no longer login as per issue #27
> > > ```
> > >   | Name | Value | Type
> > > -- | -- | -- | --
> > > ◢ | $exception | {"System.DBNull contains no definition for OuterHtml"} | Microsoft.CSharp.RuntimeBinder.RuntimeBinderException
> > > ```
> > > 
> > > 
> > > Triggers when I hit login
> > 
> > 
> > I was not able to reproduce this issue.
> > Can you try using the newest release: https://github.com/JonasNilson/idle_master_extended/releases/tag/v1.4 to see if you can get past the login step?
> 
> Tried the new release. Hit sign in, login window popped up and closed. Nothing happened.
> Hit sign in again. Login window popped up again, redirected to my steam profile and closed.
> Now everything seems to work :)
> Games are idling again as well.

If you are able to try the latest release, 1.4-final, it should have fixed the closing window issue

**Comment by SkebbZ** [comment] 2020-02-02 17:28
> 
> 
> > > > > @SkebbZ
> > > > > Could you try running Idle Master through Visual Studio and see if you can get an error message?
> > > > 
> > > > 
> > > > Tried it, but now I can no longer login as per issue #27
> > > > ```
> > > >   | Name | Value | Type
> > > > -- | -- | -- | --
> > > > ◢ | $exception | {"System.DBNull contains no definition for OuterHtml"} | Microsoft.CSharp.RuntimeBinder.RuntimeBinderException
> > > > ```
> > > > 
> > > > 
> > > > Triggers when I hit login
> > > 
> > > 
> > > I was not able to reproduce this issue.
> > > Can you try using the newest release: https://github.com/JonasNilson/idle_master_extended/releases/tag/v1.4 to see if you can get past the login step?
> > 
> > 
> > Tried the new release. Hit sign in, login window popped up and closed. Nothing happened.
> > Hit sign in again. Login window popped up again, redirected to my steam profile and closed.
> > Now everything seems to work :)
> > Games are idling again as well.
> 
> If you are able to try the latest release, 1.4-final, it should have fixed the closing window issue

Seems fine now :)

**Closed** 2020-02-17 15:38 UTC
