### ISSUE TITLE
Suggestion: Implement automatic check in case login is demanded by the status label while browser session is still active

### ISSUE THREAD

**Issue by Wolterhon** [JonasNilson/idle_master_extended#328] opened 2022-07-18 03:41 UTC
Sometimes in Idle Master at startup Steam account status is displayed as 'not logged in'. But the session is still there and if one presses the 'Log in' link to open the popup window, it'll just load the user's Steam profile and disappear in two or three seconds. The suggestion is to make it so the window is opened automatically on startup if the account status is 'not logged in' (maybe in the background somehow, without actually displaying the browser window) so there's just a bit less hassle. Must be not that hard to implement.

**Comment by Wolterhon** [comment] 2022-07-18 03:41
Terribly sorry if you're here before I've edited it, accidentally pressed enter when I was typing the title.

**Comment by JonasNilson** [comment] 2022-08-26 19:46
Thank you for your comment.

I will have to look into this once I have the time - or someone else might provide a pull request with the proper code changes to address this issue. I'm marking this as a good first issue.

**Comment by JonasNilson** [comment] 2022-08-28 13:26
My bet is that this was caused by the browser having the cookies available.

The latest release removes the browser window: https://github.com/JonasNilson/idle_master_extended/releases/tag/v1.8.0

Closing.

**Closed by JonasNilson** 2022-08-28 13:26 UTC
Labels: enhancement, good first issue
