### ISSUE TITLE
[BUG] Idle Master will pretend there are no cards left while in reality there's a problem with the cookies and there are cards to farm

### ISSUE THREAD

**Issue by Wolterhon** [JonasNilson/idle_master_extended#353] opened 2022-09-12 17:57 UTC
## Describe the bug ##
Idle Master won't start farming even if there are cards to be farmed, instead it pretends that it checks all the badge pages (which it probably does, but not from my account's perspective probably), and since my session is old it won't find any cards to farm.

## To Reproduce ##
0. Have some cards to farm.
1. Give your session details to IME and close the program probably.
2. Wait for them (session details) to expire or log out of Steam yourself to make the session expire thus making the cookies outdated.
3. Start IME. 
4. Obserhe how it checks all your badge pages and claims there are no cards left to farm.

## Expected behavior ##
When cookies given to IME are outdated, the second checkmark becomes an X and there's a 'Log In' button

**Comment by tst0** [comment] 2022-09-18 10:26
+

It does it because cookie parameters are no longer valid, you can fix with sign out and sign in again.

**Comment by Wolterhon** [comment] 2022-09-18 10:31
> It does it because cookie parameters are no longer valid, you can fix with sign out and sign in again.
At this point I could've just farmed the cards with SAM lol

**Comment by Wolterhon** [comment] 2022-09-18 10:36
> It does it because cookie parameters are no longer valid, you can fix with sign out and sign in again.

Yeah saying that it's connected to my Steam account when it clearly isn't is not a bug at all. And I know how to fix it lol, I *literally* said this in the 'Describe the bug' section.

**Comment by Clown-0914** [comment] 2022-09-18 13:42
I have the same bug happening to me.
But I logged out and logged back in and it did not heal.
[](https://media.discordapp.net/attachments/781523718320422976/1021053518548828300/57677867.PNG)

**Comment by Wolterhon** [comment] 2022-09-18 13:43
> I have the same bug happening to me. But I logged out and logged back in and it did not heal.

Try to log in to your Steam account in an incognito window and feed your incognito cookies to the program

**Comment by Marcelzocker999** [comment] 2022-09-18 15:17
Same

**Comment by JonasNilson** [comment] 2022-09-19 05:12
Thank you for your bug report. 

I will have to investigate this issue and reproduce it myself. 

Hopefully it's enough to request a renewal of the cookie from the Steam web API.

**Comment by Wolterhon** [comment] 2022-09-19 07:42
> Thank you for your bug report.
> 
> I will have to investigate this issue and reproduce it myself.
> 
> Hopefully it's enough to request a renewal of the cookie from the Steam web API.

I neither don't want to be the smartass, nor I have any proper knowledge about Steam API in particular, but there's one reliable(-ish?) way to check if you're logged in. If you are not, then steamcommunity.com/my redirects to /login/home/
Maybe that will help if there's no cleaner/reliable way to check cookies' validity.

**Comment by jonas-med-ett-s** [comment] 2023-09-18 13:17
Fixed in the latest release: https://github.com/JonasNilson/idle_master_extended/releases

**Closed by jonas-med-ett-s** 2023-09-18 13:17 UTC
Labels: bug
